name: build

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2019
    steps:
      
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu-20.04

      - shell: wsl-bash {0}
        name: Install Prerequisites
        run: sudo apt-get install -y build-essential

      - shell: wsl-bash {0}
        name: Save Build Script
        run: |
            cat << 'EOF' > ~/build.sh
            
            export MAKEFLAGS=-j2
            URL=https://www.cpan.org/src/5.0/perl-5.32.0.tar.gz
            echo Downloading and compiling in [$PWD] from [$URL]
            
            mkdir perl 
            wget -nc $URL
            tar -xf $(basename $URL) --strip-components=1 --directory=perl
            cd perl

            bash +x ./Configure -sde -Dprefix="$PWD/../prefix"
            test -f Makefile
            make
            make install
            
            EOF
      
      - shell: wsl-bash {0}
        name: Download and build Perl 5 (case-insensitive mount)
        run: bash ~/build.sh
      
      - shell: wsl-bash {0}
        name: Download and build Perl 5 (case-sensitive mount)
        if: ${{ always() }}
        run: cd ~ && bash ~/build.sh
