name: build

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2019
    steps:
      
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu-20.04
      
      - shell: wsl-bash {0}
        name: Install Prerequisites
        run: |
            sudo apt-get install -y build-essential
      
      - shell: wsl-bash {0}
        name: Download and build Perl 5 (case-sensitive mount)
        run: |
          URL=https://www.cpan.org/src/5.0/perl-5.32.0.tar.gz
          PREFIX=$PWD/prefix

          echo Downloading and compiling in [$PWD]
          mkdir -p $PREFIX perl 
          wget -nc $URL
          tar -xf $(basename $URL) --strip-components=1 --directory=perl
          cd perl

          bash +x ./Configure -sde -Dprefix=$PREFIX
          make
          make install
